# Copyright 2022-present SK Telecom
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
appVersion: "1.0.0"
description: A Helm chart example for CaaS app deployment
name: caas-app
version: 1.0.0
keywords:
  - mec
  - cluster api
  - provision
sources:
  - https://github.com/sonaproject
maintainers:
  - name: Jian Li
    email: gunine@sk.com
annotations:
  category: Infrastructure
