images:
  registry: docker.io
  repository: centos/tools
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  ## for nodeport type service specify nodePort value
  #nodePort: 30888

persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  ##
  enabled: true
  
  ## @param persistence.storageClass Persistent Volume storage class
  ## If defined, storageClassName: <storageClass>
  ## If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner
  ##
  storageClass: ""

  ## @param persistence.accessModes [array] Persistent Volume access modes
  ##
  accessModes:
    - ReadWriteOnce

  ## @param persistence.size Persistent Volume size
  ##
  size: 1Gi
  
  ## @param persistence.existingClaim The name of an existing PVC to use for persistence
  ##
  existingClaim: ""

#sriov:
#  - network: mecworker1ens3f1
#    interface: net1
#    ip: 172.30.0.120

#gpu:
#  num: 1
#  drivers: video,compute,utility

#node:
#  name: dev-worker
