images:
  registry: docker.io
  repository: centos/tools
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  ## for nodeport type service specify nodePort value
  #nodePort: 30888

#sriov:
#  - network: mecworker1ens3f1
#    interface: net1
#    ip: 172.30.0.120

#gpu:
#  num: 1
#  drivers: video,compute,utility
